apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.djangoblog.config.secretName}}
  namespace: {{.Values.djangoblog.namespaceOverride}}
  labels:
    # helm.sh/resource-policy: keep
    {{- include "djangoblog-chart.labels" . | nindent 4}}
type: Opaque
data:
  DJANGO_MYSQL_HOST: {{ include "djangoblog-chart.mysqlHost" . | trimPrefix "\n" | b64enc }} 
  {{- with .Values.mysql.auth }}
  DJANGO_MYSQL_DATABASE: {{ default "djangoblog"  .database | b64enc }} 
  DJANGO_MYSQL_USER: {{ default "root" .username | b64enc}}  
  DJANGO_MYSQL_PASSWORD:  {{ default "password" .password | b64enc }} 
  DJANGO_MYSQL_PORT: {{ "3306" | b64enc }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  DJANGO_REDIS_URL: {{ printf ":%s@%s" .Values.redis.global.redis.password (include "djangoblog-chart.redisHost" .) | b64enc }}
  {{- end }}
  ## optional fields for you to set
  # DJANGO_MEMCACHED_ENABLE: VHJ1ZQ==  # Ensure this is properly encoded
  # DJANGO_MEMCACHED_LOCATION: MTI3LjAuMC4xOjExMjEx  # Ensure this is properly encoded
  # DJANGO_BAIDU_NOTIFY_URL: aHR0cDovL2RhdGEuemoudW5pdmVyc2l0eS5jb20vdXJscy9zaXRlL3Rva2VuP3NpdGU9aHR0cHM6Ly93d3cuZXhhbXBsZS5vcmcmdG9rZW49Q0hBTkdFTUU=  # Ensure this is properly encoded
  # DJANGO_EMAIL_TLS: RmFsc2U=  # Ensure this is properly encoded
  # DJANGO_EMAIL_SSL: VHJ1ZQ==  # Ensure this is properly encoded
  # DJANGO_EMAIL_HOST: c210cC5leGFtcGxlLm9yZw==  # Ensure this is properly encoded
  # DJANGO_EMAIL_PORT: NDY1  # Ensure this is properly encoded
  # DJANGO_EMAIL_USER: xxxxxxxxxxxx # Ensure this is properly encoded
  # DJANGO_EMAIL_PASSWORD: U01QVFVTRVJfUEFTU1dPUkQ=  # Ensure this is properly encoded
  # DJANGO_ADMIN_EMAIL: xxxxxxxxxxxxxx # Ensure this is properly encoded
  # DJANGO_WEROBOT_TOKEN: xxxxxxxxxxxxxx  # Ensure this is properly encoded
  # DJANGO_ELASTICSEARCH_HOST: xxxxxxxxxxx  Ensure this is properly encoded
