apiVersion: v1
kind: Service
metadata:
  name: external-mysql
spec:
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-mysql
subsets:
- addresses:
  - ip: {{ .Values.externalDB.host}}
  ports:
  - port: {{ .Values.externalDB.port}}

