apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  selector:
    io.kompose.service: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30888
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
      name: https
    - protocol: TCP
      port: 9113
      targetPort: 9113
      name: metrics
  type: NodePort            # use NodePort only in non-production environment
