apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm0
  labels:
    io.kompose.service: nginx
  annotations:
    use-subpath: "true"
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      #keepalive_timeout  65;

      gzip  on;

      upstream blog {
        server djangoblog:8000;       # [djangoblog service name] :[port]
      }

      server {
        listen 80;
        server_name 192.168.244.33;    # [server ip]

        location / {
          proxy_pass http://blog;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
        }

        location /static/ {  
        # nginx container will search the static files under the dir /djangoblog/static/
          root /djangoblog/;  
          expires max;
        }

        location = /basic_status {  # monitor the status of nginx ,use for nginx-exporter
        stub_status;
          }
      }
    }

