apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.djangoblog.namespaceOverride }}
  labels:
    io.kompose.service: "djangoblog-claim2"
    {{- with .Values.djangoblog.persistence }}
  name: {{.claimName}}
  
spec:
  accessModes:
    - {{ .accessMode}}
  storageClassName: {{ .storageClass }}  # use your storage class name
  resources:
    requests:
      storage: {{.size }}
     {{- end }}
