apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  selector:
    io.kompose.service: redis
  ports:
    - protocol: TCP
      port: {{.Values.redis.service.port}}
      targetPort: {{.Values.redis.service.targetPort}}
      name: redis
{{- if .Values.redis.redisExporter.enabled }}
    - protocol: TCP
      port: 9121
      targetPort: 9121
      name: metrics
{{- end}}
