apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.djangoblog.config.secretName}}
  labels:
    helm.sh/resource-policy: keep
type: Opaque
data:
  DJANGO_MYSQL_DATABASE: ZGphbmdvYmxvZw== # djangoblog
  DJANGO_MYSQL_USER: cm9vdA==  # root
  DJANGO_MYSQL_PASSWORD: "pass_in_base64"  # replace it with your pass in base64
  DJANGO_MYSQL_HOST: MTkyLjE2OC4yNDQuMzM=  # external-mysql
  DJANGO_MYSQL_PORT: MzMwNg==  #  3306
  DJANGO_REDIS_URL: cmVkaXM6NjM3OQ==  # Ensure this is properly encoded
  ## optional fields for you to set
  # DJANGO_MEMCACHED_ENABLE: VHJ1ZQ==  # Ensure this is properly encoded
  # DJANGO_MEMCACHED_LOCATION: MTI3LjAuMC4xOjExMjEx  # Ensure this is properly encoded
  # DJANGO_BAIDU_NOTIFY_URL: aHR0cDovL2RhdGEuemoudW5pdmVyc2l0eS5jb20vdXJscy9zaXRlL3Rva2VuP3NpdGU9aHR0cHM6Ly93d3cuZXhhbXBsZS5vcmcmdG9rZW49Q0hBTkdFTUU=  # Ensure this is properly encoded
  # DJANGO_EMAIL_TLS: RmFsc2U=  # Ensure this is properly encoded
  # DJANGO_EMAIL_SSL: VHJ1ZQ==  # Ensure this is properly encoded
  # DJANGO_EMAIL_HOST: c210cC5leGFtcGxlLm9yZw==  # Ensure this is properly encoded
  # DJANGO_EMAIL_PORT: NDY1  # Ensure this is properly encoded
  # DJANGO_EMAIL_USER: xxxxxxxxxxxx # Ensure this is properly encoded
  # DJANGO_EMAIL_PASSWORD: U01QVFVTRVJfUEFTU1dPUkQ=  # Ensure this is properly encoded
  # DJANGO_ADMIN_EMAIL: xxxxxxxxxxxxxx # Ensure this is properly encoded
  # DJANGO_WEROBOT_TOKEN: xxxxxxxxxxxxxx  # Ensure this is properly encoded
  # DJANGO_ELASTICSEARCH_HOST: xxxxxxxxxxx  Ensure this is properly encoded
