apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: djangoblog-claim2
  name: {{.Values.djangoblog.persistence.claimName}}
spec:
  accessModes:
    - {{ .Values.djangoblog.persistence.accessMode}}
  storageClassName: {{ .Values.djangoblog.persistence.storageClass }}  # use your storage class name
  resources:
    requests:
      storage: {{.Values.djangoblog.persistence.size }}
