apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: redis
    spec:
      imagePullSecrets:
        - name: default   # replace it with your own imagePullSecrets
      containers:
        - image: "{{.Values.redis.image.repository}}:{{.Values.redis.image.tag}}"  # replace it with a specific tag
          imagePullPolicy: {{.Values.redis.image.pullPolicy}}
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          startupProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 5   # the check timeout
            periodSeconds: 10   # the check period
            failureThreshold: 5   # the maximum number of failures before the container is considered as failed
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 5   # the check timeout
            periodSeconds: 10   # the check period
            failureThreshold: 5   # the maximum number of failures before the container is considered as failed
            successThreshold: 1
   {{- if .Values.redis.redisExporter.enabled}} 
        - name: redis-exporter
          image: "{{.Values.redis.redisExporter.image.repository}}:{{.Values.redis.redisExporter.image.tag}}"
          args:
            - --redis.addr=localhost:6379
          ports:
            - containerPort: 9121
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Always
   {{- end}}

