name: Helm Chart Release

on:
  push:
    branches:
      - main



jobs:
  release:
  #  choose ubuntu-latest to run on 
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout code
    # use the prebuilt action checkout@v2 to check out code for following steps
      uses: actions/checkout@v2
      # fetch-depth: 0 is required to get the full git history
      with:
        fetch-depth: 0

    - name: configure git
      run: |
        git config --local user.name "Devin" 
        git config --local user.email "stemm@foxmail.com"

    - name: setup helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: add repo
      run: helm repo add bitnami https://charts.bitnami.com/bitnami      
    - name: update repo
      run: helm repo update
      
    - name : run chart releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
      # make sure charts exists in the root directory
        charts_dir: charts
        packages_with_index: false
        pages_branch: gh-pages
        skip_existing: false
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CR_GENERATE_RELEASE_NOTES: true
